### ISSUE TITLE
for your thought

### ISSUE THREAD

**Issue by hdk0102** [MarwanNour/SEAL-FYP-Logistic-Regression#1]
Hey Marwan!

I was looking into your codes (logistic_regression_ckks.cpp) and had two things that I wished to hear your opinion on.

First, why are you refreshing the weights (decrypt and re-encrypt) in line 358? What's the purpose?
Second, Shouldn't line 220 be num_weights and line 300 be num_observations? I think the two should be swapped.

Looking forward to hearing your opinion!

Best,
dk

**Comment by MarwanNour** [comment]
Hey DK, sorry for the late reply.
Now to answer your questions:
1 - The reason why I am refreshing the weights is because I need to re-scale the ciphertext weights and I can't do that once I reach level 0. When you re-scale, you go down by one level. So if I decrypt and re-encrypt the weights then I can get back to a decent level. 
2 - I am not sure. I need some time to double check this. It's been a while since I worked on this project so I need to review my notes.
