### ISSUE TITLE
logistic_regression_ckks.exe also raise vector size exceeds error

### ISSUE THREAD

**Issue by alexhmyang** [MarwanNour/SEAL-FYP-Logistic-Regression#4]
1. logistic_regression_ckks.exe also raise vector size exceeds error, actually train process cannot be finished , why? ( i haven't changed any code, just run the example code and example csv, logistic_regression.exe no problem)

3. logistic_regression_ckks.exe  runs train very slow, even 50 samples needs to wait half an hour, so i think for 2000 samples csv, the trainning time is not acceptable, why? 

thank you .

**Comment by MarwanNour** [comment]
To answer your questions:
1- My code is buggy and I haven't had the time to fix it (Although you're welcome to create a fork and implement your own bug fixes).
2- The training is slow mainly due to the encryption time with the CKKS scheme. I couldn't figure out a way to reduce the training time back then.
